//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ_17_5_22
{
    using System;
    using System.Collections.Generic;
    
    public partial class sv
    {
        public string mssv { get; set; }
        public string hoten { get; set; }
        public Nullable<int> lopsh_id { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public Nullable<double> dtb { get; set; }
        public Nullable<bool> anh { get; set; }
        public Nullable<bool> hocba { get; set; }
        public Nullable<bool> cmnd { get; set; }
    
        public virtual lopsh lopsh { get; set; }
    }
}
